
compile:
	$(MAKE) -C SDFS_put compile
	$(MAKE) -C SDFS_get compile
	$(MAKE) -C SDFS_ls compile
	$(MAKE) -C SDFS_rm compile

clean:
	$(MAKE) -C SDFS_put clean
	$(MAKE) -C SDFS_get clean
	$(MAKE) -C SDFS_ls clean
	$(MAKE) -C SDFS_rm clean

install:
	echo "TODO"

